// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using haihv.DatDai.Api.Services;

#nullable disable

namespace haihv.DatDai.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241102124559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("haihv.DatDai.Data.DanhMuc.Model.DvhcDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Cap")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "cap");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ghiChu");

                    b.Property<bool>("HieuLuc")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "hieuLuc");

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "loaiHinh");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "maHuyen");

                    b.Property<string>("MaKyHieu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "maDvhc");

                    b.Property<string>("MaTinh")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "maTinh");

                    b.Property<string>("MaXa")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasAnnotation("Relational:JsonPropertyName", "maXa");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "ngayHieuLuc");

                    b.Property<string>("TenGiaTri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tenDvhc");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.ToTable("DvhcDtos");
                });
#pragma warning restore 612, 618
        }
    }
}
